# Generated by Django 6.0.1 on 2026-01-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=20)),
                ('area_asignada', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
