# Generated by Django 6.0.1 on 2026-02-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='dias_trabajados',
            field=models.PositiveIntegerField(default=0, verbose_name='Días Cumplidos'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='guardia',
            name='horas_trabajadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Horas Totales'),
        ),
    ]
