# Generated by Django 6.0.1 on 2026-06-25 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0002_guardia_dias_trabajados_guardia_estatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardia',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='guardia',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='dias_trabajados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='estatus',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='horas_trabajadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='turno',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ROBO', 'Robo / Hurto'), ('FALLA', 'Falla de Infraestructura (Luz, Agua, Estructura)'), ('PERDIDA', 'Pérdida de Bienes'), ('ALTERCADO', 'Altercado / Pelea'), ('OTROS', 'Otros Eventos')], default='OTROS', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción de la novedad')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del evento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='seguridad_unellez.guardia', verbose_name='Guardia que reporta')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
