# Generated by Django 6.0.1 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0004_guardia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardia',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
    ]
