# Generated by Django 6.0.1 on 2026-07-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0005_alter_guardia_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
