# Generated by Django 6.0.1 on 2026-07-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0006_guardia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='esta_bloqueado',
            field=models.BooleanField(default=False, verbose_name='¿Cuenta Bloqueada?'),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='estatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pendiente', 'Pendiente'), ('Inactivo', 'Inactivo'), ('Bloqueado', 'Bloqueado')], default='Activo', max_length=20),
        ),
    ]
