# Generated by Django 6.0.1 on 2026-07-09 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0007_guardia_esta_bloqueado_alter_guardia_estatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso Remunerado'), ('LICENCIA', 'Licencia por Salud / Familiar'), ('CAMBIO_TURNO', 'Cambio de Turno')], default='VACACIONES', max_length=20, verbose_name='Tipo de Solicitud')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('motivo', models.TextField(verbose_name='Justificación / Motivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15, verbose_name='Estado de Petición')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='seguridad_unellez.guardia', verbose_name='Oficial solicitante')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que revisó')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
