# Generated by Django 6.0.1 on 2026-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0008_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='archivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_incidencias/', verbose_name='Archivo de Evidencia (Imagen/Video)'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='area_suceso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación o Área'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='titulo',
            field=models.CharField(default='Reporte de Guardia', max_length=200, verbose_name='Título o Asunto'),
        ),
    ]
