# Generated by Django 6.0.1 on 2026-07-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0009_incidencia_archivo_evidencia_incidencia_area_suceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Mensaje')),
                ('area_destino', models.CharField(help_text='Ej: Pabellón III, General', max_length=100, verbose_name='Área de destino')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='seguridad_unellez.guardia')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
