# Generated by Django 6.0.1 on 2026-07-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_unellez', '0010_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardia',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='guardia',
            name='apellido',
            field=models.CharField(default='Sin Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='guardia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='archivo_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_incidencias/', verbose_name='Archivo de Evidencia'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='area_destino',
            field=models.CharField(max_length=100, verbose_name='Área de destino'),
        ),
    ]
